import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SmoothScroll from "@/components/SmoothScroll";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,600,700,800&f[]=author@300,400,500,600,700&f[]=bespoke-stencil@400,500&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="font-author antialiased">
        <SmoothScroll>
          
          <Navbar />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
